services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - books-net
    volumes:
      - mysql-volume:/var/lib/mysql
  phonebook:
    image: bookstoreapi
    container_name: phonebook
    networks:
      - books-net
    ports:
      - "80:80"
    depends_on:
      - database
    restart: always
volumes:
  mysql-volume:
networks:
  books-net: